import { mkdir, writeFile } from "node:fs/promises";
import { ENTITIES } from "../../lib/manufacturing/model.ts";
const types = { text: "text", select: "text", number: "numeric", boolean: "boolean", link: "bigint", date: "timestamptz", json: "jsonb" };
const requirementLocationColumns = `,
  part_location text,
  location_updated_by text,
  location_updated_at timestamptz,
  constraint requirements_part_location_check check (part_location is null or part_location in (
    'Clarke 1','Clarke 2','Clarke 3','Clarke 4','Clarke 5','Clarke 6','Clarke 7','Clarke 8',
    'Kwolek 1-1','Kwolek 1-2','Kwolek 1-3','Kwolek 1-4','Kwolek 1-5','Kwolek 1-6','Kwolek 1-7','Kwolek 1-8',
    'Kwolek 2-1','Kwolek 2-2','Kwolek 2-3','Kwolek 2-4','Kwolek 2-5','Kwolek 2-6','Kwolek 2-7','Kwolek 2-8',
    'Hopper 1','Hopper 2','Hopper 3','Hopper 4','Hopper 5','Hopper 6','Hopper 7','Hopper 8',
    'Jemison 1-1','Jemison 1-2','Jemison 1-3','Jemison 1-4','Jemison 1-5','Jemison 1-6','Jemison 1-7','Jemison 1-8',
    'Jemison 2-1','Jemison 2-2','Jemison 2-3','Jemison 2-4','Jemison 2-5','Jemison 2-6','Jemison 2-7','Jemison 2-8',
    'Shelf 1','Shelf 2','Shelf 3','On Robot'
  )),
  constraint requirements_location_attribution_check check (
    (location_updated_by is null) = (location_updated_at is null)
  )`;
let sql = `-- Additive production-candidate schema. Apply explicitly; no live cutover.
begin;
create schema manufacturing;
revoke all on schema manufacturing from public, anon, authenticated;
create table manufacturing.locations (
  id bigint generated by default as identity primary key,
  baserow_id bigint unique, location_key text unique not null,
  name text not null, description text, active boolean not null default true,
  created_at timestamptz not null default now()
);
`;
for (const entity of ENTITIES) {
  sql += `create table manufacturing.${entity.name} (
  id bigint generated by default as identity primary key,
  baserow_id bigint unique,
  source_snapshot_id uuid references frc190_baserow_stage.snapshots(id),
  source_row jsonb not null default '{}'::jsonb,
  location_id bigint references manufacturing.locations(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ${entity.columns.map(([name,,kind]) => name + " " + types[kind]).join(",\n  ")}${entity.name === "requirements" ? requirementLocationColumns : ""},
  check (baserow_id is null or baserow_id = id)
);
create index ${entity.name}_key_idx on manufacturing.${entity.name} (${entity.key});
`;
  if (entity.name !== "operations") sql += `create unique index ${entity.name}_key_unique on manufacturing.${entity.name} (${entity.key}) where ${entity.key} is not null and ${entity.key} <> '';
`;
}
sql += `
alter table manufacturing.requirements add foreign key (part_id) references manufacturing.parts(id),
  add foreign key (assembly_id) references manufacturing.assemblies(id);
alter table manufacturing.operations add foreign key (requirement_id) references manufacturing.requirements(id);
alter table manufacturing.finishing add foreign key (requirement_id) references manufacturing.requirements(id);
create index operations_requirement_idx on manufacturing.operations(requirement_id);
create index finishing_requirement_idx on manufacturing.finishing(requirement_id);
create table manufacturing.operation_allocations (
  operation_id bigint not null references manufacturing.operations(id),
  ordinal integer not null,
  user_id text not null, display_name text not null,
  claimed numeric not null, completed numeric not null,
  source_allocation jsonb not null,
  primary key (operation_id, ordinal)
);
comment on table manufacturing.operation_allocations is 'Imported ledger entries retain original identities, including legacy assignments; never resolved by display name';
create table manufacturing.imports (
  snapshot_id uuid primary key references frc190_baserow_stage.snapshots(id),
  imported_at timestamptz not null default now(), counts jsonb not null
);
`;
for (const name of ["locations", ...ENTITIES.map(e => e.name), "operation_allocations", "imports"]) {
  sql += `alter table manufacturing.${name} enable row level security;
revoke all on manufacturing.${name} from public, anon, authenticated, service_role;
`;
}
sql += `
-- No schema exposure/config change. Server-side reads use this bounded RPC.
create function public.manufacturing_read_entity(p_entity text, p_offset integer default 0, p_limit integer default 500)
returns jsonb language plpgsql stable security definer set search_path = '' as $read$
declare result jsonb;
begin
  if p_entity not in ('assemblies','parts','requirements','operations','finishing','locations')
     or p_offset < 0 or p_limit < 1 or p_limit > 500 then raise exception 'Invalid manufacturing page'; end if;
  execute format('select jsonb_build_object(''rows'', coalesce((select jsonb_agg(to_jsonb(r)) from
    (select * from manufacturing.%I order by id offset $1 limit $2) r), ''[]''::jsonb),
    ''total'', (select count(*) from manufacturing.%I))', p_entity, p_entity)
    into result using p_offset, p_limit;
  return result;
end;
$read$;
revoke all on function public.manufacturing_read_entity(text,integer,integer) from public, anon, authenticated;
grant execute on function public.manufacturing_read_entity(text,integer,integer) to service_role;
commit;
`;
await mkdir("supabase/production", { recursive: true });
await writeFile("supabase/production/20260905_normalized_manufacturing.sql", sql);
console.log("Generated additive normalized manufacturing schema");
