-- Private attachment catalog for binaries copied from Baserow to Supabase
-- Storage. Apply after the normalized manufacturing schema.
begin;

create table manufacturing.attachments (
  id bigint generated by default as identity primary key,
  part_id bigint not null references manufacturing.parts(id) on delete restrict,
  kind text not null check (kind in ('drawing-pdf', 'step')),
  position integer not null check (position >= 0),
  source_field_id bigint not null,
  source_url text not null,
  source_metadata jsonb not null,
  original_name text not null,
  content_type text not null,
  byte_size bigint not null check (byte_size >= 0),
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  storage_bucket text not null,
  storage_path text not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default clock_timestamp(),
  unique (part_id, kind, position),
  unique (source_url)
);
create index attachments_part_kind_idx on manufacturing.attachments(part_id, kind, position);
alter table manufacturing.attachments enable row level security;
revoke all on manufacturing.attachments from public, anon, authenticated, service_role;
revoke all on sequence manufacturing.attachments_id_seq from public, anon, authenticated, service_role;

create function public.manufacturing_register_attachment(
  p_part_id bigint,
  p_kind text,
  p_position integer,
  p_source_field_id bigint,
  p_source_url text,
  p_source_metadata jsonb,
  p_original_name text,
  p_content_type text,
  p_byte_size bigint,
  p_sha256 text,
  p_storage_bucket text,
  p_storage_path text,
  p_verified_at timestamptz
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare existing manufacturing.attachments; attachment_id bigint;
begin
  if p_kind not in ('drawing-pdf', 'step') or p_position < 0
    or p_source_url !~ '^https://' or coalesce(p_original_name, '') = ''
    or coalesce(p_content_type, '') = '' or p_byte_size < 0
    or p_sha256 !~ '^[0-9a-f]{64}$' or p_storage_bucket <> 'manufacturing-files'
    or p_storage_path !~ '^sha256/[0-9a-f]{2}/[0-9a-f]{64}\.(pdf|step)$'
    or p_source_metadata is null or p_verified_at is null then
    raise exception 'Invalid manufacturing attachment';
  end if;
  if not exists(select 1 from manufacturing.parts where id = p_part_id) then
    raise exception 'Attachment part is missing' using errcode = '23503';
  end if;

  select * into existing from manufacturing.attachments
  where (part_id, kind, position) = (p_part_id, p_kind, p_position)
     or source_url = p_source_url
  for update;
  if found then
    if existing.part_id is distinct from p_part_id or existing.kind is distinct from p_kind
      or existing.position is distinct from p_position or existing.source_field_id is distinct from p_source_field_id
      or existing.source_url is distinct from p_source_url or existing.source_metadata is distinct from p_source_metadata
      or existing.original_name is distinct from p_original_name or existing.content_type is distinct from p_content_type
      or existing.byte_size is distinct from p_byte_size or existing.sha256 is distinct from p_sha256
      or existing.storage_bucket is distinct from p_storage_bucket or existing.storage_path is distinct from p_storage_path then
      raise exception 'Attachment registration conflicts with verified data' using errcode = '40001';
    end if;
    return existing.id;
  end if;

  insert into manufacturing.attachments(
    part_id, kind, position, source_field_id, source_url, source_metadata,
    original_name, content_type, byte_size, sha256, storage_bucket,
    storage_path, verified_at
  ) values (
    p_part_id, p_kind, p_position, p_source_field_id, p_source_url,
    p_source_metadata, p_original_name, p_content_type, p_byte_size, p_sha256,
    p_storage_bucket, p_storage_path, p_verified_at
  ) returning id into attachment_id;
  return attachment_id;
end;
$$;
revoke all on function public.manufacturing_register_attachment(bigint,text,integer,bigint,text,jsonb,text,text,bigint,text,text,text,timestamptz)
  from public, anon, authenticated;
grant execute on function public.manufacturing_register_attachment(bigint,text,integer,bigint,text,jsonb,text,text,bigint,text,text,text,timestamptz)
  to service_role;

create function public.manufacturing_file_for_requirement(p_requirement_id bigint, p_kind text)
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'bucket', a.storage_bucket,
    'path', a.storage_path,
    'name', a.original_name,
    'content_type', a.content_type,
    'byte_size', a.byte_size,
    'sha256', a.sha256
  )
  from manufacturing.requirements r
  join manufacturing.attachments a on a.part_id = r.part_id
  where r.id = p_requirement_id and a.kind = p_kind
  order by a.position, a.id
  limit 1;
$$;
revoke all on function public.manufacturing_file_for_requirement(bigint,text) from public, anon, authenticated;
grant execute on function public.manufacturing_file_for_requirement(bigint,text) to service_role;

create function public.manufacturing_attachment_manifest()
returns jsonb language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'part_id', part_id,
    'kind', kind,
    'position', position,
    'source_field_id', source_field_id,
    'source_url', source_url,
    'original_name', original_name,
    'content_type', content_type,
    'byte_size', byte_size,
    'sha256', sha256,
    'storage_bucket', storage_bucket,
    'storage_path', storage_path
  ) order by part_id, kind, position), '[]'::jsonb)
  from manufacturing.attachments;
$$;
revoke all on function public.manufacturing_attachment_manifest() from public, anon, authenticated;
grant execute on function public.manufacturing_attachment_manifest() to service_role;

commit;
