alter table public.quality_control
  drop constraint quality_control_pkey;

alter table public.quality_control
  add column id bigint generated by default as identity primary key,
  add column production_requirement_id bigint,
  alter column operation_id drop not null;

alter table public.quality_control
  add constraint quality_control_has_source
  check (production_requirement_id is not null or operation_id is not null);

create index quality_control_requirement_reviewed_at_idx
  on public.quality_control (production_requirement_id, reviewed_at desc);
