-- Add a requirement-level production note, an append-only revision log for
-- both note types, and a write boundary available to every approved shop user.
begin;

alter table manufacturing.requirements
  add column if not exists production_notes text not null default '';

create table if not exists manufacturing.requirement_note_revisions (
  id bigint generated by default as identity primary key,
  requirement_id bigint not null references manufacturing.requirements(id) on delete restrict,
  request_id uuid not null references manufacturing.write_requests(request_id) on delete restrict,
  note_kind text not null check (note_kind in ('production', 'inspection')),
  previous_text text not null,
  new_text text not null,
  changed_by uuid not null references auth.users(id) on delete restrict,
  changed_at timestamptz not null
);

create index if not exists requirement_note_revisions_requirement_changed_idx
  on manufacturing.requirement_note_revisions(requirement_id, changed_at desc, id desc);

alter table manufacturing.requirement_note_revisions enable row level security;
revoke all on manufacturing.requirement_note_revisions from public, anon, authenticated, service_role;

drop trigger if exists immutable on manufacturing.requirement_note_revisions;
create trigger immutable before update or delete or truncate on manufacturing.requirement_note_revisions
  for each statement execute function manufacturing.prevent_history_change();

create or replace function manufacturing.record_requirement_note_revision()
returns trigger
language plpgsql
set search_path = ''
as $revision$
declare
  revision_actor uuid;
  revision_time timestamptz;
begin
  if new.entity <> 'requirements' then return new; end if;

  select actor, committed_at into revision_actor, revision_time
  from manufacturing.write_requests
  where request_id = new.request_id;

  if coalesce(new.before_row->>'production_notes', '') is distinct from coalesce(new.after_row->>'production_notes', '') then
    insert into manufacturing.requirement_note_revisions(
      requirement_id, request_id, note_kind, previous_text, new_text, changed_by, changed_at
    ) values (
      new.row_id, new.request_id, 'production', coalesce(new.before_row->>'production_notes', ''),
      coalesce(new.after_row->>'production_notes', ''), revision_actor, revision_time
    );
  end if;

  if coalesce(new.before_row->>'qc_notes', '') is distinct from coalesce(new.after_row->>'qc_notes', '') then
    insert into manufacturing.requirement_note_revisions(
      requirement_id, request_id, note_kind, previous_text, new_text, changed_by, changed_at
    ) values (
      new.row_id, new.request_id, 'inspection', coalesce(new.before_row->>'qc_notes', ''),
      coalesce(new.after_row->>'qc_notes', ''), revision_actor, revision_time
    );
  end if;

  return new;
end;
$revision$;

revoke all on function manufacturing.record_requirement_note_revision() from public, anon, authenticated, service_role;

drop trigger if exists record_requirement_note_revision on manufacturing.write_history;
create trigger record_requirement_note_revision
  after insert on manufacturing.write_history
  for each row execute function manufacturing.record_requirement_note_revision();

create or replace function public.manufacturing_update_requirement_notes(
  p_request_id uuid,
  p_actor uuid,
  p_expected text,
  p_requirement_id bigint,
  p_notes text,
  p_result jsonb
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $notes$
declare
  prior manufacturing.write_requests;
  fingerprint text;
  before_row jsonb;
  after_row jsonb;
begin
  set local lock_timeout = '5s';
  lock table manufacturing.write_control, manufacturing.write_requests,
    manufacturing.requirements, manufacturing.write_history in share row exclusive mode;

  if not exists(select 1 from manufacturing.write_control where enabled) then
    raise exception 'Supabase manufacturing writes are disabled' using errcode = '42501';
  end if;
  if not exists(select 1 from public.profiles where id = p_actor and approved for share) then
    raise exception 'Approved actor required' using errcode = '42501';
  end if;
  if p_request_id is null or p_notes is null or char_length(p_notes) > 5000 then
    raise exception 'Invalid production note';
  end if;

  fingerprint := md5(jsonb_build_array(p_actor, p_expected, p_requirement_id, p_notes, p_result)::text);
  select * into prior from manufacturing.write_requests where request_id = p_request_id;
  if found then
    if prior.payload_hash <> fingerprint then
      raise sqlstate 'PT409' using message = 'Request ID reused with different payload';
    end if;
    return prior.result;
  end if;

  if p_expected is distinct from md5(manufacturing.write_snapshot()::text) then
    raise sqlstate 'PT409' using message = 'Manufacturing state changed';
  end if;

  select to_jsonb(r) into before_row
  from manufacturing.requirements r
  where r.id = p_requirement_id;
  if before_row is null then
    raise sqlstate 'PT409' using message = 'Production requirement no longer exists';
  end if;

  insert into manufacturing.write_requests(request_id, actor, action, payload_hash, result)
  values(p_request_id, p_actor, 'requirement_note', fingerprint, p_result);

  update manufacturing.requirements r
  set production_notes = p_notes,
      updated_at = clock_timestamp()
  where r.id = p_requirement_id
  returning to_jsonb(r) into after_row;

  insert into manufacturing.write_history(request_id, entity, row_id, before_row, after_row)
  values(p_request_id, 'requirements', p_requirement_id, before_row, after_row);

  return p_result;
end;
$notes$;

revoke all on function public.manufacturing_update_requirement_notes(uuid,uuid,text,bigint,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.manufacturing_update_requirement_notes(uuid,uuid,text,bigint,text,jsonb)
  to service_role;

commit;
