-- Private GLB derivatives generated from the authoritative STEP attachments.
-- Apply after 20260905_manufacturing_attachments.sql. The browser never reads
-- this table or the Storage bucket directly; approved-user application routes
-- resolve and stream previews with the server-side secret key.
begin;

create table manufacturing.part_previews (
  id bigint generated by default as identity primary key,
  part_id bigint not null unique references manufacturing.parts(id) on delete restrict,
  source_attachment_id bigint not null unique references manufacturing.attachments(id) on delete cascade,
  source_sha256 text not null check (source_sha256 ~ '^[0-9a-f]{64}$'),
  generator text not null check (generator <> ''),
  generator_version text not null check (generator_version <> ''),
  content_type text not null check (content_type = 'model/gltf-binary'),
  byte_size bigint not null check (byte_size > 0),
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  storage_bucket text not null check (storage_bucket = 'manufacturing-files'),
  storage_path text not null check (storage_path ~ '^sha256/[0-9a-f]{2}/[0-9a-f]{64}\.glb$'),
  verified_at timestamptz not null,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp()
);
alter table manufacturing.part_previews enable row level security;
revoke all on manufacturing.part_previews from public, anon, authenticated, service_role;
revoke all on sequence manufacturing.part_previews_id_seq from public, anon, authenticated, service_role;

create function public.manufacturing_register_part_preview(
  p_source_attachment_id bigint,
  p_source_sha256 text,
  p_generator text,
  p_generator_version text,
  p_content_type text,
  p_byte_size bigint,
  p_sha256 text,
  p_storage_bucket text,
  p_storage_path text,
  p_verified_at timestamptz
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  source manufacturing.attachments;
  preview_id bigint;
begin
  select * into source
  from manufacturing.attachments
  where id = p_source_attachment_id
  for share;

  if not found or source.kind <> 'step' then
    raise exception 'Preview source STEP attachment is missing' using errcode = '23503';
  end if;
  if source.sha256 is distinct from p_source_sha256
    or coalesce(p_generator, '') = '' or coalesce(p_generator_version, '') = ''
    or p_content_type <> 'model/gltf-binary' or p_byte_size <= 0
    or p_sha256 !~ '^[0-9a-f]{64}$' or p_storage_bucket <> 'manufacturing-files'
    or p_storage_path <> 'sha256/' || left(p_sha256, 2) || '/' || p_sha256 || '.glb'
    or p_verified_at is null then
    raise exception 'Invalid manufacturing part preview';
  end if;

  insert into manufacturing.part_previews(
    part_id, source_attachment_id, source_sha256, generator,
    generator_version, content_type, byte_size, sha256, storage_bucket,
    storage_path, verified_at
  ) values (
    source.part_id, source.id, source.sha256, p_generator,
    p_generator_version, p_content_type, p_byte_size, p_sha256,
    p_storage_bucket, p_storage_path, p_verified_at
  )
  on conflict (part_id) do update set
    source_attachment_id = excluded.source_attachment_id,
    source_sha256 = excluded.source_sha256,
    generator = excluded.generator,
    generator_version = excluded.generator_version,
    content_type = excluded.content_type,
    byte_size = excluded.byte_size,
    sha256 = excluded.sha256,
    storage_bucket = excluded.storage_bucket,
    storage_path = excluded.storage_path,
    verified_at = excluded.verified_at,
    updated_at = clock_timestamp()
  returning id into preview_id;

  return preview_id;
end;
$$;
revoke all on function public.manufacturing_register_part_preview(bigint,text,text,text,text,bigint,text,text,text,timestamptz)
  from public, anon, authenticated;
grant execute on function public.manufacturing_register_part_preview(bigint,text,text,text,text,bigint,text,text,text,timestamptz)
  to service_role;

create function public.manufacturing_step_preview_sources()
returns jsonb language sql stable security definer set search_path = '' as $$
  with selected_steps as (
    select distinct on (a.part_id)
      a.id, a.part_id, a.original_name, a.byte_size, a.sha256,
      a.storage_bucket, a.storage_path
    from manufacturing.attachments a
    where a.kind = 'step'
    order by a.part_id, a.position, a.id
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'attachment_id', a.id,
    'part_id', a.part_id,
    'original_name', a.original_name,
    'byte_size', a.byte_size,
    'sha256', a.sha256,
    'storage_bucket', a.storage_bucket,
    'storage_path', a.storage_path,
    'preview_source_sha256', p.source_sha256,
    'preview_generator', p.generator,
    'preview_generator_version', p.generator_version,
    'preview_byte_size', p.byte_size,
    'preview_sha256', p.sha256,
    'preview_storage_bucket', p.storage_bucket,
    'preview_storage_path', p.storage_path
  ) order by a.part_id), '[]'::jsonb)
  from selected_steps a
  left join manufacturing.part_previews p on p.part_id = a.part_id;
$$;
revoke all on function public.manufacturing_step_preview_sources() from public, anon, authenticated;
grant execute on function public.manufacturing_step_preview_sources() to service_role;

create function public.manufacturing_preview_for_requirement(p_requirement_id bigint)
returns jsonb language sql stable security definer set search_path = '' as $$
  with selected_step as (
    select a.*
    from manufacturing.requirements r
    join manufacturing.attachments a on a.part_id = r.part_id
    where r.id = p_requirement_id and a.kind = 'step'
    order by a.position, a.id
    limit 1
  )
  select jsonb_build_object(
    'bucket', p.storage_bucket,
    'path', p.storage_path,
    'content_type', p.content_type,
    'byte_size', p.byte_size,
    'sha256', p.sha256,
    'source_sha256', p.source_sha256
  )
  from selected_step a
  join manufacturing.part_previews p
    on p.source_attachment_id = a.id and p.source_sha256 = a.sha256;
$$;
revoke all on function public.manufacturing_preview_for_requirement(bigint) from public, anon, authenticated;
grant execute on function public.manufacturing_preview_for_requirement(bigint) to service_role;

create function public.manufacturing_preview_manifest()
returns jsonb language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'part_id', part_id,
    'source_attachment_id', source_attachment_id,
    'source_sha256', source_sha256,
    'generator', generator,
    'generator_version', generator_version,
    'content_type', content_type,
    'byte_size', byte_size,
    'sha256', sha256,
    'storage_bucket', storage_bucket,
    'storage_path', storage_path
  ) order by part_id), '[]'::jsonb)
  from manufacturing.part_previews;
$$;
revoke all on function public.manufacturing_preview_manifest() from public, anon, authenticated;
grant execute on function public.manufacturing_preview_manifest() to service_role;

commit;
