-- Additive production-candidate schema. Apply explicitly; no live cutover.
begin;
create schema manufacturing;
revoke all on schema manufacturing from public, anon, authenticated;
create table manufacturing.locations (
  id bigint generated by default as identity primary key,
  baserow_id bigint unique, location_key text unique not null,
  name text not null, description text, active boolean not null default true,
  created_at timestamptz not null default now()
);
create table manufacturing.assemblies (
  id bigint generated by default as identity primary key,
  baserow_id bigint unique,
  source_snapshot_id uuid references frc190_baserow_stage.snapshots(id),
  source_row jsonb not null default '{}'::jsonb,
  location_id bigint references manufacturing.locations(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  assembly_number text,
  subsystem_name text,
  active boolean,
  notes text,
  sync_schema_version text,
  check (baserow_id is null or baserow_id = id)
);
create index assemblies_key_idx on manufacturing.assemblies (assembly_number);
create unique index assemblies_key_unique on manufacturing.assemblies (assembly_number) where assembly_number is not null and assembly_number <> '';
create table manufacturing.parts (
  id bigint generated by default as identity primary key,
  baserow_id bigint unique,
  source_snapshot_id uuid references frc190_baserow_stage.snapshots(id),
  source_row jsonb not null default '{}'::jsonb,
  location_id bigint references manufacturing.locations(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  part_number text,
  name text,
  description text,
  material text,
  manufacturing_method text,
  vendor text,
  revision text,
  onshape_url text,
  category text,
  drawing_url text,
  drawing_files jsonb,
  step_files jsonb,
  drawing_export_key text,
  step_export_key text,
  active boolean,
  last_synced_at timestamptz,
  check (baserow_id is null or baserow_id = id)
);
create index parts_key_idx on manufacturing.parts (part_number);
create unique index parts_key_unique on manufacturing.parts (part_number) where part_number is not null and part_number <> '';
create table manufacturing.requirements (
  id bigint generated by default as identity primary key,
  baserow_id bigint unique,
  source_snapshot_id uuid references frc190_baserow_stage.snapshots(id),
  source_row jsonb not null default '{}'::jsonb,
  location_id bigint references manufacturing.locations(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  production_key text,
  part_id bigint,
  assembly_id bigint,
  configuration text,
  required_quantity numeric,
  bom_positions text,
  onshape_url text,
  source_document text,
  source_root text,
  source_assembly_revision text,
  required_part_revision text,
  machine_op1 text,
  machine_op2 text,
  machine_op3 text,
  machine_op4 text,
  finishing text,
  active_in_bom boolean,
  engineering_changed boolean,
  last_synced_at timestamptz,
  status text,
  machinist text,
  qc_outcome text,
  qc_notes text,
  qc_reviewed_by text,
  qc_reviewed_at timestamptz,
  disposition text,
  part_location text,
  location_updated_by text,
  location_updated_at timestamptz,
  constraint requirements_part_location_check check (part_location is null or part_location in (
    'Clarke 1','Clarke 2','Clarke 3','Clarke 4','Clarke 5','Clarke 6','Clarke 7','Clarke 8',
    'Kwolek 1-1','Kwolek 1-2','Kwolek 1-3','Kwolek 1-4','Kwolek 1-5','Kwolek 1-6','Kwolek 1-7','Kwolek 1-8',
    'Kwolek 2-1','Kwolek 2-2','Kwolek 2-3','Kwolek 2-4','Kwolek 2-5','Kwolek 2-6','Kwolek 2-7','Kwolek 2-8',
    'Hopper 1','Hopper 2','Hopper 3','Hopper 4','Hopper 5','Hopper 6','Hopper 7','Hopper 8',
    'Jemison 1-1','Jemison 1-2','Jemison 1-3','Jemison 1-4','Jemison 1-5','Jemison 1-6','Jemison 1-7','Jemison 1-8',
    'Jemison 2-1','Jemison 2-2','Jemison 2-3','Jemison 2-4','Jemison 2-5','Jemison 2-6','Jemison 2-7','Jemison 2-8',
    'Shelf 1','Shelf 2','Shelf 3','On Robot'
  )),
  constraint requirements_location_attribution_check check (
    (location_updated_by is null) = (location_updated_at is null)
  ),
  check (baserow_id is null or baserow_id = id)
);
create index requirements_key_idx on manufacturing.requirements (production_key);
create unique index requirements_key_unique on manufacturing.requirements (production_key) where production_key is not null and production_key <> '';
create table manufacturing.operations (
  id bigint generated by default as identity primary key,
  baserow_id bigint unique,
  source_snapshot_id uuid references frc190_baserow_stage.snapshots(id),
  source_row jsonb not null default '{}'::jsonb,
  location_id bigint references manufacturing.locations(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  operation_key text,
  requirement_id bigint,
  operation_number text,
  machine text,
  work_type text,
  active_in_routing boolean,
  status text,
  machinist text,
  started_at timestamptz,
  completed_at timestamptz,
  claimed_quantity numeric,
  completed_quantity numeric,
  quantity_ledger text,
  cam_program_path text,
  cam_notes text,
  check (baserow_id is null or baserow_id = id)
);
create index operations_key_idx on manufacturing.operations (operation_key);
create table manufacturing.finishing (
  id bigint generated by default as identity primary key,
  baserow_id bigint unique,
  source_snapshot_id uuid references frc190_baserow_stage.snapshots(id),
  source_row jsonb not null default '{}'::jsonb,
  location_id bigint references manufacturing.locations(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  production_key text,
  requirement_id bigint,
  color text,
  required_quantity numeric,
  active boolean,
  last_synced_at timestamptz,
  machinist text,
  check (baserow_id is null or baserow_id = id)
);
create index finishing_key_idx on manufacturing.finishing (production_key);
create unique index finishing_key_unique on manufacturing.finishing (production_key) where production_key is not null and production_key <> '';

alter table manufacturing.requirements add foreign key (part_id) references manufacturing.parts(id),
  add foreign key (assembly_id) references manufacturing.assemblies(id);
alter table manufacturing.operations add foreign key (requirement_id) references manufacturing.requirements(id);
alter table manufacturing.finishing add foreign key (requirement_id) references manufacturing.requirements(id);
create index operations_requirement_idx on manufacturing.operations(requirement_id);
create index finishing_requirement_idx on manufacturing.finishing(requirement_id);
create table manufacturing.operation_allocations (
  operation_id bigint not null references manufacturing.operations(id),
  ordinal integer not null,
  user_id text not null, display_name text not null,
  claimed numeric not null, completed numeric not null,
  source_allocation jsonb not null,
  primary key (operation_id, ordinal)
);
comment on table manufacturing.operation_allocations is 'Imported ledger entries retain original identities, including legacy assignments; never resolved by display name';
create table manufacturing.imports (
  snapshot_id uuid primary key references frc190_baserow_stage.snapshots(id),
  imported_at timestamptz not null default now(), counts jsonb not null
);
alter table manufacturing.locations enable row level security;
revoke all on manufacturing.locations from public, anon, authenticated, service_role;
alter table manufacturing.assemblies enable row level security;
revoke all on manufacturing.assemblies from public, anon, authenticated, service_role;
alter table manufacturing.parts enable row level security;
revoke all on manufacturing.parts from public, anon, authenticated, service_role;
alter table manufacturing.requirements enable row level security;
revoke all on manufacturing.requirements from public, anon, authenticated, service_role;
alter table manufacturing.operations enable row level security;
revoke all on manufacturing.operations from public, anon, authenticated, service_role;
alter table manufacturing.finishing enable row level security;
revoke all on manufacturing.finishing from public, anon, authenticated, service_role;
alter table manufacturing.operation_allocations enable row level security;
revoke all on manufacturing.operation_allocations from public, anon, authenticated, service_role;
alter table manufacturing.imports enable row level security;
revoke all on manufacturing.imports from public, anon, authenticated, service_role;

-- No schema exposure/config change. Server-side reads use this bounded RPC.
create function public.manufacturing_read_entity(p_entity text, p_offset integer default 0, p_limit integer default 500)
returns jsonb language plpgsql stable security definer set search_path = '' as $read$
declare result jsonb;
begin
  if p_entity not in ('assemblies','parts','requirements','operations','finishing','locations')
     or p_offset < 0 or p_limit < 1 or p_limit > 500 then raise exception 'Invalid manufacturing page'; end if;
  execute format('select jsonb_build_object(''rows'', coalesce((select jsonb_agg(to_jsonb(r)) from
    (select * from manufacturing.%I order by id offset $1 limit $2) r), ''[]''::jsonb),
    ''total'', (select count(*) from manufacturing.%I))', p_entity, p_entity)
    into result using p_offset, p_limit;
  return result;
end;
$read$;
revoke all on function public.manufacturing_read_entity(text,integer,integer) from public, anon, authenticated;
grant execute on function public.manufacturing_read_entity(text,integer,integer) to service_role;
commit;
